In [1]:
import pandas as pd
import os

In [2]:
# Read a vcf file
def read_vcf(vcf_path):
    with open(vcf_path, "rt") as ifile:
        for line in ifile:
            if line.startswith("#CHROM"):
                vcf_names = [x for x in line.split('\t')]
                break
    ifile.close()
    data = pd.read_csv(vcf_path, comment='#', sep="\s+", header=None, names=vcf_names)
    data['POS'] =  data[['#CHROM','POS']].apply(lambda x : '{}.{}'.format(x[0],x[1]).replace("chr",""), axis=1)
    data=data.drop(['#CHROM','ID', 'REF', 'ALT','QUAL','FILTER','INFO','FORMAT'], axis=1)
    return data

In [3]:
os.chdir("impute5_test")

In [4]:
missing_postfix=".missing.vcf"
original_postfix=".ori.vcf"
imputed_postfix=".missing.vcf.final.vcf"

In [5]:
sample="HLA1_chr6.all.0.25"

In [6]:
missing=read_vcf(sample+missing_postfix)
missing.head(10)

,POS,HG00096,HG00097,HG00099,HG00100,HG00101,HG00102,HG00103,HG00105,HG00106,...,NA21128,NA21129,NA21130,NA21133,NA21135,NA21137,NA21141,NA21142,NA21143,NA21144\n
0,6.292119,0|0,.|.,0|0,0|0,.|.,0|0,0|0,0|0,0|0,...,0|0,0|0,.|.,0|0,0|0,0|0,.|.,0|0,.|.,0|0
1,6.292179,0|0,.|.,0|0,0|0,.|.,0|0,0|0,0|0,0|0,...,.|.,0|0,0|0,0|0,0|0,0|0,0|1,0|0,0|0,0|0
2,6.292235,.|.,.|.,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,.|.,.|.,0|0,0|0,.|.,.|.,0|0,0|0
3,6.292280,0|0,0|0,0|0,0|0,0|0,0|0,.|.,0|0,0|0,...,.|.,0|0,.|.,0|0,.|.,.|.,0|0,0|0,0|0,.|.
4,6.292329,.|.,0|0,.|.,.|.,.|.,0|0,0|0,0|0,0|0,...,.|.,0|0,0|0,0|0,0|0,.|.,0|0,0|0,0|0,.|.
5,6.292342,0|0,.|.,0|0,.|.,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,.|.,0|0,.|.,.|.,0|0,0|0,0|0,.|.
6,6.292349,0|0,.|.,0|0,0|0,0|0,.|.,.|.,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,.|.,0|0
7,6.292474,0|0,0|0,.|.,0|0,.|.,.|.,0|0,0|0,0|0,...,.|.,0|0,.|.,0|0,.|.,0|0,0|0,.|.,0|0,.|.
8,6.292619,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,.|.,0|0,.|.,0|0,0|0,0|0,.|.,0|0,0|0,0|0
9,6.292658,0|0,.|.,0|0,0|0,0|0,0|0,.|.,.|.,0|0,...,0|0,0|0,.|.,0|0,0|0,0|0,0|0,.|.,.|.,0|0

In [7]:
imputed=read_vcf(sample+imputed_postfix)
imputed.head(10)

,POS,HG00096,HG00097,HG00099,HG00100,HG00101,HG00102,HG00103,HG00105,HG00106,...,NA21128,NA21129,NA21130,NA21133,NA21135,NA21137,NA21141,NA21142,NA21143,NA21144\n
0,6.292113,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
1,6.292119,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
2,6.292149,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
3,6.292150,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
4,6.292179,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|1,0|0,0|0,0|0
5,6.292235,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
6,6.292279,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
7,6.292280,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
8,6.292329,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
9,6.292342,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0

In [8]:
original=read_vcf(sample+original_postfix)
original.head(10)

,POS,HG00096,HG00097,HG00099,HG00100,HG00101,HG00102,HG00103,HG00105,HG00106,...,NA21128,NA21129,NA21130,NA21133,NA21135,NA21137,NA21141,NA21142,NA21143,NA21144\n
0,6.292119,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
1,6.292179,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|1,0|0,0|0,0|0
2,6.292235,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
3,6.292280,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
4,6.292329,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
5,6.292342,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
6,6.292349,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
7,6.292474,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
8,6.292619,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
9,6.292658,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0

In [9]:
print(imputed.shape)
print(original.shape)
print(missing.shape)

(2383, 2505)
(1058, 2505)
(1058, 2505)

In [10]:
true_position=list(original['POS'])

In [11]:
wrong_with_missing=0 # check if non-hidden allele change from missing file
wrong_with_original=0 # check if hidden allele different from original file
wrong_position=0# check if it has position not in origin
missing_count=0

for i in range(imputed.shape[0]):
    if imputed.iloc[i]['POS'] not in true_position:
        wrong_position+=1
        continue
    position_in_original=true_position.index(imputed.iloc[i]['POS'])
    for j in range(1,imputed.shape[1]):
        if missing.iloc[position_in_original,j] == ".|.":
            missing_count+=2
            if original.iloc[position_in_original,j] != imputed.iloc[i,j]:
                origin_diplo = original.iloc[position_in_original,j]
                imputed_diplo = imputed.iloc[i,j]
                if imputed_diplo[0]!=origin_diplo[0]:
                    wrong_with_original += 1
                if imputed_diplo[2]!=origin_diplo[2]:
                    wrong_with_original += 1 
        else:
            if missing.iloc[position_in_original,j] != imputed.iloc[i,j]:
                missing_diplo = missing.iloc[position_in_original,j]
                imputed_diplo = imputed.iloc[i,j]
                if imputed_diplo[0]!=missing_diplo[0]:
                    wrong_with_missing += 1
                if imputed_diplo[2]!=missing_diplo[2]:
                    wrong_with_missing += 1

In [12]:
total_position=original.shape[1]*(original.shape[0]-1)*2
print("Total allele: {}".format(total_position))
print("Change non-missing position in missing vcf: {:.2f}% ({})".format(wrong_with_missing/total_position*100,wrong_with_missing))
print("Different from original with missing position: {:.2f}% ({})".format(wrong_with_original/total_position*100,wrong_with_original))
print("Create new position from original: {}".format(wrong_position))
accuracy=(1-(wrong_with_missing+wrong_with_original)/total_position)*100
print("Accuracy Total: {:.2f}%".format(accuracy))
accuracy_on_missing=(1-wrong_with_original/missing_count)*100
print("Accuracy On Missing: {:.2f}%".format(accuracy_on_missing))

Total allele: 5295570
Change non-missing position in missing vcf: 0.00% (19)
Different from original with missing position: 1.57% (83245)
Create new position from original: 1325
Accuracy Total: 98.43%
Accuracy On Missing: 93.72%